### ISSUE TITLE
TypeError: Object of type <class 'NoneType'> is not TOML serializable

### ISSUE THREAD

**Issue by amotl** [hukkin/tomli-w#39]
Dear Taneli,

thanks a stack for conceiving and maintaining this excellent library. We just wanted to let you know about an issue we just discovered when serializing `NoneType` values [1]. We are aware that TOML does not know about any kinds of NULL values (https://github.com/toml-lang/toml/issues/921).

Differently than #34, this issue is merely a proposal to handle `NoneType` values gracefully by just ignoring them on serialization. The [`toml`](https://pypi.org/project/toml/) package does just that [2]. We have exercised the situation with all of `toml`, `tomlkit`, and `tomli-w` on behalf of a unit test at [3] and also reported the same issue to the author of `tomlkit` at https://github.com/sdispater/tomlkit/issues/240.

With kind regards,
Andreas.

[1] https://github.com/isarengineering/SecPi/issues/25
[2] https://github.com/isarengineering/SecPi/pull/27
[3] https://gist.github.com/amotl/4d8bc928d781a5d0fbc7f404396f8417

**Comment by amotl** [comment]
We also found that, when using the access pattern to directly serialize to a file,
```python
with open("testdrive.toml", "wb") as config_file:
    tomli_w.dump(data, config_file)
```

`tomli-w` raises an exception, but still writes the file up to the point where the error happens, when `data` contains any `NoneType` value. The test at [3] demonstrates it for easy reproduction.

**Comment by hukkin** [comment]
Hey there, thanks for the issue!

I think it's better to be strict than graceful when non serializable objects are found. If a consumer of Tomli-W needs to ignore `None`s, it is trivial for them to write a wrapper function something like the following (completely untested):
```python
def remove_nones(d):
    if isinstance(d, dict):
        return {k: remove_nones(v) for k, v in d.items() if v is not None}
    return d

def write_toml_ignoring_none(d):
    return tomli_w.dumps(remove_nones(d))

```

The function `write_toml_ignoring_none` should do what you want.

**Comment by amotl** [comment]
Dear Taneli,

thank you very much for taking the time to respond to my request. I think it is fine to defer ignoring NULL values to userspace.

However, you may want to revisit my comment at https://github.com/hukkin/tomli-w/issues/39#issuecomment-1256731965. I think it indicates that it may happen that `tomli-w` writes invalid/incomplete TOML.

With kind regards,
Andreas.
