### ISSUE TITLE
Idea: add comment support?

### ISSUE THREAD

**Issue by FObersteiner** [hukkin/tomli-w#45]
I was wondering if it would be feasible to output comments?

Why? I wrote some code that generates a "reference" config file, with all the keys available to configure an application. I thought that it would be nice to have a comment to each key with some explanation of possible values and what the key does.

**Comment by hukkin** [comment]
Hi there! I don't plan to support comments, but tomlkit already does support them: https://github.com/sdispater/tomlkit
