### ISSUE TITLE
Add `sort_keys` option

### ISSUE THREAD

**Issue by CaoGitHubUser** [hukkin/tomli-w#48]
As a prettier option and a **big** improval for tests that compare a toml file, I think a `sort_keys` like `json` option is useful.It ensure two toml file with same content will be able to do a text-compare after sorting keys.

**Comment by hukkin** [comment]
Thanks for the issue!

As the README file mentions, Tomli-W respects sort order of the input dict, so you can do
```python
import tomli_w

def order_dict(d):
    return {k: order_dict(v) if isinstance(v, dict) else v for k, v in sorted(d.items())}

d = {"b": 2, "a": {"b": 2, "a": 1}}
sorted_toml = tomli_w.dumps(order_dict(d))
```

It's trivial enough to come up with a sort function of your own that I'm not sure Tomli-W needs to ship with one (that may not sort exactly the way you want).
