### ISSUE TITLE
Pathlib.Path objects not serializable

### ISSUE THREAD

**Issue by murphlmao** [hukkin/tomli-w#50]
It would be nice if pathlib.Path objects were serializable by default:

```py
import pathlib
import tomli_w

root_dir = pathlib.Path("/")

data = {
    "target": {
        "ip": "xx.xx.xx.xx",
        "os": {
            "os": "win 10",
            "Arch": "x64",
            "root directory": root_dir # throws TypeError. would need to do str(root_dir)
        },
        "ports": {
            "ports": ["1", "2"],
            "1": {
                "service": "xxx",
                "ver": "5.9",
            }
        }
    }
}

output_file_name = "test.toml"
with open(output_file_name, "wb") as toml_file:
    tomli_w.dump(data, toml_file)
```

Very small QOL thing, but it would still be nice to not have to wrap each value in (str).

**Comment by hukkin** [comment]
Thanks for the issue!

TOML doesn't have a filepath type so I don't want to support this. In theory we could call `str` on any type, but I'd rather be strict and limit us to types that match with something in TOML spec. It should be fairly straightforward to convert pathlib Paths prior to a `tomli_w.dump` call.
