### ISSUE TITLE
Improve error message for ill formed toml key

### ISSUE THREAD

**Issue by oliversheridanmethven** [hukkin/tomli-w#53]
`tomli_w.dumps({"1": 1})` works fine, but when the key is numeric, such as passing in `{1:1}` I get a `TypeError` about iterability. The error message is pretty hard to decipher. Similarly if I pass in `None` as the key the complaint is about not being subscriptable. I think these errors could be improved with a type check and be better reported.

**Comment by hukkin** [comment]
Thanks for the issue! I've improved the error message in https://github.com/hukkin/tomli-w/pull/62
