### ISSUE TITLE
Handling of integer keys

### ISSUE THREAD

**Issue by hcording** [hukkin/tomli-w#54]
The TOML spec says integer keys are supported, but interpreted as strings.

`tomli_w.dumps({1: "a"})` produces `TypeError: 'int' object is not iterable`.

And `tomli.loads('1 = "a"')` gives `{"1": "a"}`.

But since in Python we support integer keys in dictionaries, I would find it intuitive that `tomli_w.dumps({1: "a"})` evaluates to:

```toml
1 = "a"
```

Otherwise the user is forced to always cast the keys to str first.

If you think this doesn't make sense, consider this example:
`tomli_w.dumps({("a", "b"): "a"})`, which gives `'(\'a\', \'b\') = "a"\n'`.

Here, we don't have to cast the key of type `tuple[str, str]` to `str` first, the library does this by itself.
So, why not offer this feature for `int` as well?

Edit: The automatic conversion in the tuple example seems to be a bug, because the resulting TOML cannot be loaded with tomli/tomllib.

It would still be useful to have automatic handling of int imo.

**Comment by hukkin** [comment]
Hey, thanks for the issue!

I don't really want to open this can of worms. A key in TOML is always interpreted as a string, even if it can sometimes look exactly like an integer, local date, boolean, or some other TOML type. I think it's fine to always expect a string key, and that is expressed in type hints too.

We have to draw the line somewhere, else we end up calling the `str()` function on any arbitrary types used as keys. I don't think that's good or safe design. Also, if someone has a mapping with really loosely typed keys that they want to print out with Tomli-W, it's trivial to come up with a function that returns a copy with keys converted to `str`. So the problem can be solved by the user. On the flipside, if Tomli-W did the conversions, there is nothing the user can do to bring back the strictness and safety of not converting.

As you mention, the fact that keys that are of type `tuple[str, ...]` where `len(str) == 1` apparently seem to work is definitely not a feature. It's just that these tuples behave very much like strings, so no errors occur. I don't really consider this a bug either, rather just undefined behavior: garbage in, garbage out.

This is a good example of why the README warns that Tomli-W output may not be valid TOML, given bad input. Another such case I can think of is if someone comes up with with their own subtype of a type Tomli-W supports and overrides the `__str__` function.
